### PR TITLE
after 'npm install' on Aurélien's PC

### PR DESCRIPTION
**Pull request by apupier**
create PR to have an overview of the differences

### CODE REVIEW

**Comment by lhein** [comment]
Which npm version have u installed?

**Comment by apupier** [comment]
> Which npm version have u installed?

6.7.0

**Comment by lhein** [comment]
that could explain it

**Comment by apupier** [comment]
I upgraded to npm 6.14.6 which corresponds to latest LTS of node and I still have the package.lock.json staying as in the master

**Comment by lhein** [comment]
as long as u don't try with the same version we will never know if its npm.

**Comment by apupier** [comment]
tried with npm 6.14.8 and still keeping the same package-lock

> as long as u don't try with the same version we will never know if its npm.

you could have also tried yourself with the 2 versions I mentioned.

**Comment by lhein** [comment]
ok, so the problem is somewhere else if it is a problem at all and not just a reordering of the contents.

**Comment by apupier** [comment]
closing as work on it has stopped

**Pull request closed without merging**
